baseURL = "http://example.org/"
languageCode = "en-us"
theme = "kugadi-simple"
title = "My New Hugo Site"
enableRobotsTXT = "true"

[permalinks]
  blog = "/blog/:year/:month/:day/:slug"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "BLOG"
    url = "/blog/"
    weight = 1
