baseURL = "https://www.kugadi.com"
languageCode = "en-us"
theme = "kugadi-simple"
title = "Kugadi"
enableRobotsTXT = "true"

[permalinks]
  blog = "/blog/:year/:month/:day/:slug"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "BLOG"
    url = "/blog/"
    weight = 1

  [[menu.main]]
    identifier = "features"
    name = "FEATURES"
    url = "#"
    weight = 1
